# 项目根目录下的 mkdocs.yml
site_name: 我的项目文档

extra:
  version:
    provider: mike
    default: stable

plugins:
  - search
  - mike:
      alias_type: symlink
      redirect_template: null
      canonical_version: null
  # 📌 加上下面这段（检查链接）
  - htmlproofer:
      raise_error: true
      validate_external_urls: true
