site_name: iOS Traffic Intel
theme: readthedocs

nav:
  - Home: index.md
  - CLI Reference: CLI.md
  - Structure: structure.md
  - Go-ios Integration: GOIOS_INTEGRATION.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
